import { Business, Customer, Product, KhataEntry, AIActionProposal } from "@/types";

export const MOCK_BUSINESS: Business = {
  id: "biz_001",
  name: "Sri Lakshmi Enterprises",
  tradeType: "wholesale",
  gstin: "33AABCS1429B1ZB",
  phone: "+91 98401 23456",
  city: "Coimbatore",
  state: "Tamil Nadu",
  currency: "INR",
};

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust_01",
    name: "Murugan Traders",
    phone: "9842109876",
    city: "Tiruppur",
    gstin: "33AABCT9981A1Z1",
    outstandingBalance: 142500, // ₹1,42,500 due
    creditLimit: 200000,
    lastActive: "2026-09-19",
    status: "overdue",
  },
  {
    id: "cust_02",
    name: "Kavitha Electricals & Hardware",
    phone: "9443211223",
    city: "Erode",
    gstin: "33AAECK4412K1Z9",
    outstandingBalance: 48200,
    creditLimit: 100000,
    lastActive: "2026-09-20",
    status: "active",
  },
  {
    id: "cust_03",
    name: "Balaji Motors & Spares",
    phone: "9789012345",
    city: "Salem",
    gstin: "33AAFCB8810M1Z4",
    outstandingBalance: 0,
    creditLimit: 150000,
    lastActive: "2026-09-18",
    status: "settled",
  },
  {
    id: "cust_04",
    name: "Raja Engineering Works",
    phone: "9944123890",
    city: "Coimbatore",
    outstandingBalance: 86400,
    creditLimit: 100000,
    lastActive: "2026-09-14",
    status: "overdue",
  },
  {
    id: "cust_05",
    name: "Anand Agencies",
    phone: "9894056781",
    city: "Pollachi",
    outstandingBalance: 12500,
    creditLimit: 50000,
    lastActive: "2026-09-21",
    status: "active",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_01",
    name: "Copper Winding Wire 1.2mm (25kg Roll)",
    sku: "WW-COP-12",
    hsn: "8544",
    category: "Electrical",
    stock: 4,
    minStockAlert: 10,
    unit: "Rolls",
    costPrice: 18500,
    sellingPrice: 22400,
    gstRate: 18,
    status: "low_stock",
  },
  {
    id: "prod_02",
    name: "Heavy Duty Submersible Pump 5HP",
    sku: "PUMP-5HP-3PH",
    hsn: "8413",
    category: "Motors & Pumps",
    stock: 14,
    minStockAlert: 5,
    unit: "Units",
    costPrice: 16200,
    sellingPrice: 19800,
    gstRate: 18,
    status: "in_stock",
  },
  {
    id: "prod_03",
    name: "Industrial Ball Bearing 6205-2RS",
    sku: "BRG-6205-2RS",
    hsn: "8482",
    category: "Mechanical",
    stock: 0,
    minStockAlert: 25,
    unit: "Pieces",
    costPrice: 140,
    sellingPrice: 210,
    gstRate: 18,
    status: "out_of_stock",
  },
  {
    id: "prod_04",
    name: "Brass Connector Terminal Block 100A",
    sku: "TRM-BRS-100",
    hsn: "8536",
    category: "Electrical",
    stock: 120,
    minStockAlert: 30,
    unit: "Pieces",
    costPrice: 85,
    sellingPrice: 135,
    gstRate: 18,
    status: "in_stock",
  },
  {
    id: "prod_05",
    name: "V-Belt B-64 Industrial Grade",
    sku: "VBLT-B64-IND",
    hsn: "4010",
    category: "Mechanical",
    stock: 8,
    minStockAlert: 15,
    unit: "Pieces",
    costPrice: 280,
    sellingPrice: 420,
    gstRate: 18,
    status: "low_stock",
  },
];

export const MOCK_KHATA_ENTRIES: KhataEntry[] = [
  {
    id: "kht_01",
    customerId: "cust_01",
    customerName: "Murugan Traders",
    customerPhone: "9842109876",
    type: "give_credit",
    amount: 65000,
    date: "2026-09-12",
    dueDate: "2026-09-19",
    note: "Invoice #INV-2026-881 (25kg Wire rolls)",
    status: "overdue",
  },
  {
    id: "kht_02",
    customerId: "cust_02",
    customerName: "Kavitha Electricals & Hardware",
    customerPhone: "9443211223",
    type: "got_payment",
    amount: 30000,
    date: "2026-09-20",
    note: "UPI Payment ref: 428192003810",
    status: "cleared",
  },
  {
    id: "kht_03",
    customerId: "cust_04",
    customerName: "Raja Engineering Works",
    customerPhone: "9944123890",
    type: "give_credit",
    amount: 86400,
    date: "2026-09-08",
    dueDate: "2026-09-15",
    note: "Invoice #INV-2026-874 (Motors order)",
    status: "overdue",
  },
];

export const MOCK_AI_PROPOSALS: AIActionProposal[] = [
  {
    id: "act_001",
    type: "send_payment_reminder",
    title: "Send WhatsApp Payment Reminder",
    targetEntity: "Murugan Traders",
    what: "Send automated payment reminder with UPI payment link for overdue amount",
    details: {
      "Customer": "Murugan Traders",
      "Phone": "+91 98421 09876",
      "Overdue Balance": "₹1,42,500",
      "Days Overdue": "7 days",
      "Channel": "WhatsApp (Tamil + English)",
    },
    consequences: "Murugan Traders will receive a polite statement and payment QR on WhatsApp. Ledgers remain unchanged until payment is recorded.",
    status: "pending",
  },
  {
    id: "act_002",
    type: "reorder_stock",
    title: "Draft Purchase Order for Low Stock",
    targetEntity: "Copper Winding Wire (25kg Roll)",
    what: "Generate draft Purchase Order for primary supplier Supreme Metals",
    details: {
      "Product": "Copper Winding Wire 1.2mm",
      "Current Stock": "4 Rolls (Threshold: 10)",
      "Suggested Reorder": "15 Rolls",
      "Estimated Total": "₹2,77,500",
    },
    consequences: "Will create a Draft Purchase Order in Supply module. Requires manual final approval before sending to supplier.",
    status: "pending",
  },
];
